/**
 * Created by alex on 22.09.17.
 */
export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const RECEIVE_SIZES = 'RECEIVE_SIZES'
export const UPDATE_CURRENT_CATEGORIE = 'UPDATE_CURRENT_CATEGORIE'
export const UPDATE_CURRENT_SIZE = 'UPDATE_CURRENT_SIZE'
